---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gpro
resources:
  - namespace.yaml
  - ./gpro-production/ks.yaml
  - ./gpro-main/ks.yaml
components:
  - ../../components/common
