apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: network
stringData:
    api-token: ENC[AES256_GCM,data:L/H4NRa/gsmTJqLnAs78XvnJSq1Otujm+kAtF2PhIJ6Ix0KLcyBBekVcK/VPamK3JX/jqNA=,iv:+X6f2HKNTi+T9rjxZtBhYDrQzRuK12KxbrmEHJg96Oc=,tag:UokQeMX+UOOUBgKtgmNryg==,type:str]
    shadowmorph-api-token: ENC[AES256_GCM,data:h2utjezSxCO0a7UFrYsua/Yg5bTn0D7DxRxNQY72Mcl/nEMmtXoVgSqi1b0QCi2DjqjbR74=,iv:4cxjV6t01J8JJIumEioLDcQ9+mSe/WYHKFyKoVvOLwc=,tag:ZcPpG/1vVCcZV0N0y4lO9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVZENzlibmprZ2g3NUY4
            U3Rma1JUb2lqb2VFY1ozR1Vqdi9YMHNUclFzCmNoV2FDM2F6U1dyNFNIbC80K0g1
            TkFFUk9neW1BcWN2c3loeXRDUDdDbWMKLS0tIFhMVzNZa1pzb3J6K09Ic3FHQk9M
            UXJLWGJYSmYvVkdNZXduRnZnU0Eyc0UKpU8fbL8HKdG8mnYINP4aVNUoj5k5+jcP
            8lUC0k9Za+R89HGQABLyIsIVlNMJMt4BP74h0JEQuZMdcNuqWbIu7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T08:01:41Z"
    mac: ENC[AES256_GCM,data:6ehRLyCybdO+y7Y8nlFdO7QIMVWBokyv2HCRhbwPa0Q3oXg2uOteAYHWuplcG8MtLUv1u/BSsYyXN9XQltst2iwyWtIMeTqCYVvVLrMyL30xX7czLWPW31Wi3KiOJ1Y3o32qZ1J0zgOzxmTU4WQdPxWy1qb5C2g7h2JKYaehGEk=,iv:HUMhn+V3jrCoZhJIEzsh1qBrswU5jI5hhZqP1BAG7Zg=,tag:ZNrVtSas+/4K9RwtvhaU7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
