apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: network
stringData:
    api-token: ENC[AES256_GCM,data:L/H4NRa/gsmTJqLnAs78XvnJSq1Otujm+kAtF2PhIJ6Ix0KLcyBBekVcK/VPamK3JX/jqNA=,iv:+X6f2HKNTi+T9rjxZtBhYDrQzRuK12KxbrmEHJg96Oc=,tag:UokQeMX+UOOUBgKtgmNryg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVZENzlibmprZ2g3NUY4
            U3Rma1JUb2lqb2VFY1ozR1Vqdi9YMHNUclFzCmNoV2FDM2F6U1dyNFNIbC80K0g1
            TkFFUk9neW1BcWN2c3loeXRDUDdDbWMKLS0tIFhMVzNZa1pzb3J6K09Ic3FHQk9M
            UXJLWGJYSmYvVkdNZXduRnZnU0Eyc0UKpU8fbL8HKdG8mnYINP4aVNUoj5k5+jcP
            8lUC0k9Za+R89HGQABLyIsIVlNMJMt4BP74h0JEQuZMdcNuqWbIu7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T08:03:08Z"
    mac: ENC[AES256_GCM,data:1jfTeCe91aDMjQmFQSqu5ZDOtAtC5sFISy7Gqu7DYfvkQc0QodwFdmBe7RE2G1lWZelJc4bvnM+ENpSrwamMgIZWZYBQUfhTe+NQ1Fsu/G0AUKJP7Aetg0FDH4mk1qbiva+KXElO2smvH8bK74eguGccVpE+cmytcnJiolF/1i0=,iv:eeJJ3qyWylSExYY5T9arztSq5YAnLhePYz6DgWq3XLU=,tag:AEa8RLAkIlR5nNYON5xdKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
