---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: autoposter
  namespace: flux-system
spec:
  image: harbor.vaderrp.com/operinko-labs/autoposter
  interval: 5m
  secretRef:
    name: harbor-image-reflector
