---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - secret-ssh.sops.yaml
  - external-secret-harbor.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
