apiVersion: v1
kind: Secret
metadata:
  name: flux-image-automation-ssh
  namespace: flux-system
type: Opaque
stringData:
  identity: ENC[AES256_GCM,data:OAgJkFeZxnQGmsUYhPK8dnIa+9lwQNx2F5KbOu2MOSa4oUSO/oNxkZQvgwjgGwrP0eq1tj0wg04wJX/CMwB68pMqdaYQ9joKS/cr05KXgO43T1KMW6fQEX6kqdua2/0czCKWZhi4Z3R/JambM+ffoIQuj9KmNQzr6Ns8Fu/tPa6X719xgwO+y0c4yysOfar2Jcyo/X+FsPyVanw16GL1roO2lu0f7NO39aEgfOgFuYxW/m8tZfkPe96q/GtLq/Qz35uc3fHSRd1mnkvU0KX+6WqrqZavKw/ccHMXEulCY5iJevfSqE5KqpSAnVabmYm41Lc8+OjnlEKPMiv+M5yLxdwSQwaAdFCc6QfjZ4NsxnYuMpAZNcSfieKXhoshwEBZx5//Jw5gB9/7Syp0OJjYl4XlBFyjXyflFKHMcwHDBuN4Op26GitLIgi18Vl8gIGlmJ0+shp6P+U9sOD97+6lliSVVAIs1gDbpKr+NRpVqqZcX2lW09Qc/BQ8lmRuWqba6SgYxbCyE1pRrwqrp9IrMlfDGtXC23tU6Gik,iv:ZtjCLno8CROHZnebn1hgoi9AzQxpd6dRY6LxMn+/TLk=,tag:gwkbGBgToItN0Jnjk1HCoQ==,type:str]
  identity.pub: ENC[AES256_GCM,data:4WqDGAIKuy6eidYZdaVYmh6DvLL0nZO/si3pxx30evM/pUkekTBw9QYnz3MW2r3lJ+EMfp4M1Ly7MojvEarU26OZn+UeVDTnAdMk9CVSeRrf1DyJ0Ph3zV7k0aFyPQrfYJ6D9E29,iv:bLfhXrTrWjdkJVnhVo8n5nhIO7lWimxlZUsqMSa6Vi0=,tag:zk6mROgzcdowCxUDmu3dHQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:EUDiuRBx3TS1WPXwFGR6DsVqNxymFH/FCsOiXyzv2emzEhLY0vssSHwi4zqeZbm/JC0fYg8LhlFajbUTHRdAKuRuOiOUYOoy1ND5yah54+B+LDoAmbAVRjuhDSR0,iv:gochd7IV4bI946nf959zjr5rOKE+U0rhhhVHqf77Bhc=,tag:qS++aTWI2Q2fS9ykSolxjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWVVHbnZHUVhGSzliZ29H
        RytLS1NjeHFoamVlQTFlQU8yeGI2eU1oZjM0Cm9iMWVyV2F5dnRiaEVzU3ludG1i
        cU14VmJrNk9RWnBQMzJSNzdFYUpNd0kKLS0tIDRPVHJhZ2RUZDE3ZlpTU2hMbVli
        RSt2QnFIY1BlMkNoUy9ZNk8rNmdTcDQKBYJSBzj8F2Tbb4RvsR3TrSrNWZ4dg10Y
        onuJyehxQZYQfAAy0Zw7YGe/COSTFx1tYb/VN+0H3VhKpZ6yaF/nNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-26T12:25:32Z"
  mac: ENC[AES256_GCM,data:MRdQ6NoYBty8zMJQgQKPT7oi8vudY9rSbhAbMk5QjC5ZCGwc4JiF16F3L8rKQZi1qj6p2Bz5Sne6q4uUW1tfsf7zJEDeyQyZ5zudq3ay4a2F5QSPLD9A8zrfn6oeG5QlMhfoFyMpoEj5ISiRPfO07GxD7m171xwKTqXFZWeuKqk=,iv:QWfGq2FjthiXwdzRhiNaf8oepn9cbFZvT+M2LvTeS2k=,tag:rKLN8r312Mu+1vQ7DwqdYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
