---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trilium-secret
  namespace: tools
spec:
  refreshInterval: 1h
  target:
    name: trilium-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        TRILIUM_OAUTH_CLIENT_ID: "{{ .client_id }}"
        TRILIUM_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: dbddf928-7c6a-49cb-93dc-37bb7b4285da
        property: TRILIUM_OAUTH_CLIENT_ID
    - secretKey: client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: dbddf928-7c6a-49cb-93dc-37bb7b4285da
        property: TRILIUM_OAUTH_CLIENT_SECRET
