---
apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: syslog-tcp
      port: 6514
      targetPort: 6514
      protocol: TCP
