---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumegressgatewaypolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: stalwart-smtp-egress
spec:
  selectors:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: stalwart
          io.kubernetes.pod.namespace: mail
  destinationCIDRs:
    - "0.0.0.0/0"
  excludedCIDRs:
    - "10.42.0.0/16"
    - "10.96.0.0/16"
    - "172.16.8.0/24"
    - "192.168.0.0/16"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: talos7
    interface: wg0
