---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-secret
  namespace: mail
spec:
  refreshInterval: 1h
  target:
    name: stalwart-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        STALWART_RECOVERY_ADMIN: "admin:{{ .initial_admin_password }}"
  data:
    - secretKey: initial_admin_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: initial_admin_password
