---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-easy-secret
  namespace: network
spec:
  refreshInterval: 1h
  target:
    name: wg-easy-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PASSWORD_HASH
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: wg_easy_password_hash
