---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bulwark-secret
  namespace: mail
spec:
  refreshInterval: 1h
  target:
    name: bulwark-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: bulwark_secret
    - secretKey: ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: bulwark_admin_password
