---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ruskonkesateatteri
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: ruskonkesateatteri
  table: "*"
  username: ruskonkesateatteri
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: leo
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: leo
  table: "*"
  username: leo
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: dmarc
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: dmarc
  table: "*"
  username: dmarc
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ruoka
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: ruoka
  table: "*"
  username: ruoka
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: medikabalans
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: medikabalans
  table: "*"
  username: medikabalans
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: kyronautopalvelu
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb
  privileges: ["ALL PRIVILEGES"]
  database: kyronautopalvelu
  table: "*"
  username: kyronautopalvelu
