---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ruskonkesateatteri
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb-ha
  name: ruskonkesateatteri
  passwordSecretKeyRef:
    name: mariadb-ruskonkesateatteri
    key: password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: leo
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb-ha
  name: leo
  passwordSecretKeyRef:
    name: mariadb-leo
    key: password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ruoka
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb-ha
  name: ruoka
  passwordSecretKeyRef:
    name: mariadb-ruoka
    key: password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: medikabalans
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb-ha
  name: medikabalans
  passwordSecretKeyRef:
    name: mariadb-medikabalans
    key: password
  maxUserConnections: 20
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: kyronautopalvelu
  namespace: database
spec:
  cleanupPolicy: Skip
  mariaDbRef:
    name: mariadb-ha
  name: kyronautopalvelu
  passwordSecretKeyRef:
    name: mariadb-kyronautopalvelu
    key: password
  maxUserConnections: 20
