apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    apitoken: ENC[AES256_GCM,data:lxh7Cxkin1j8BmGPZFXkzhzUoqBZA+A8S6TVJCpGOnnzU8L9tJDJdQ==,iv:BuuXZikmkrM8D8haeJ9Da2RbgV54TpY42qUn+ELY9IQ=,tag:lAqZtUC2TNBrhxaqD1V0Dw==,type:str]
    shadowmorph-api-token: ENC[AES256_GCM,data:akMu9rkEblItxT/kqoOEJD9zO0QJRCos2WI7XZ8ALJhoo0uUJhWC/ClLYDX28iIzcAmk8rE=,iv:+hr0hl84bEVnsKlWIbNrDDL3e7D4HOBirHsehggL4QM=,tag:86rIeb0jSFRSWAfuY2xgOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNzdxTWRnQUt1bkZEcGtj
            TzRSWFhEbm1LZzlGK3VyMEdNZEt1MWFxTDBNCkZBRWpubzQ3d29QOTNZd2d6RXlS
            Skg5dENrcDJrNFdmSUN6cjNPcE5aSTAKLS0tIGdnck9qZjVKdHRiMndiZTNYNzE4
            c3J2MFZxOWxXU1dRNmF6WC9JQ0U2ZTQKUzQK2TpuTSJ6ZBZ11LI2m8JmRzUCxQ8e
            iEk9/IaqDc1oevHp93alcd/CydiQjpYph7c4pL94EwRWzFmXf4JuGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T11:22:01Z"
    mac: ENC[AES256_GCM,data:EXf7u6xdh2s/v2aH/GclfWjR7PaAg+hSQOK+hYAWsMDGhYJ3W0oc/WPA/O+SjtauySJ2ol7jt88WfxEBET7/ErVGejUulU6K/I9Lox6nrF/1eqxwlbSBOgqluCntyAwEbfMeZp9ge8nKvRDMgmWAh76RdcTUYUBhXm+liF0phNI=,iv:aWgAwyYM33c6MjMp+kVRLUfWAY54VYtnJLImME/x6Eo=,tag:mEhkoE8GVBF81a4nB6rMiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
