apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    apitoken: ENC[AES256_GCM,data:mPcb+h+iUjli8igB0MVSbYcTAf2NBMaLAjfcM2tfCZAmrLUNlizdpHqFsxmYGph0gK3K0dE=,iv:aOUUc+2mu6oRpwoX6PuzaG/yYc2pYdb7CkBFkSE4r4c=,tag:NsV/qrckeXkuhXsuAkSNZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNzdxTWRnQUt1bkZEcGtj
            TzRSWFhEbm1LZzlGK3VyMEdNZEt1MWFxTDBNCkZBRWpubzQ3d29QOTNZd2d6RXlS
            Skg5dENrcDJrNFdmSUN6cjNPcE5aSTAKLS0tIGdnck9qZjVKdHRiMndiZTNYNzE4
            c3J2MFZxOWxXU1dRNmF6WC9JQ0U2ZTQKUzQK2TpuTSJ6ZBZ11LI2m8JmRzUCxQ8e
            iEk9/IaqDc1oevHp93alcd/CydiQjpYph7c4pL94EwRWzFmXf4JuGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T10:00:08Z"
    mac: ENC[AES256_GCM,data:TW66kPjdP2aQUvXFno8x844BzdMKaaNxJtNY8girXh/QFxbJq8FogP4j48ueiaHrYT+Pt5s7DnfQemK2Pbn2RL1Gjw5Cv5NYsH0wioLTjY+9z5bPtynl6xuZaUHHfNS+S6E4IpumEpHWvjQ5G4cDOm1PCLdAPWoq5zw+CGgabX8=,iv:uTDqdRit/UVjz1ZvhdWRHjAIK2i98f653HIAHipvtMA=,tag:ZC5ByHHk/noITmeV+DwzKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
