apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    apitoken: ENC[AES256_GCM,data:lxh7Cxkin1j8BmGPZFXkzhzUoqBZA+A8S6TVJCpGOnnzU8L9tJDJdQ==,iv:BuuXZikmkrM8D8haeJ9Da2RbgV54TpY42qUn+ELY9IQ=,tag:lAqZtUC2TNBrhxaqD1V0Dw==,type:str]
    shadowmorph-api-token: ENC[AES256_GCM,data:akMu9rkEblItxT/kqoOEJD9zO0QJRCos2WI7XZ8ALJhoo0uUJhWC/ClLYDX28iIzcAmk8rE=,iv:+hr0hl84bEVnsKlWIbNrDDL3e7D4HOBirHsehggL4QM=,tag:86rIeb0jSFRSWAfuY2xgOw==,type:str]
    erinko-api-token: ENC[AES256_GCM,data:DDtPc/T72kNXXPBERY7zO/eccT7TeGBR49tjjb69P3yFVfpx3zJHbOIcOrbLP9zGhNlYX1c=,iv:B02JOcPE3rpsh0I9hWmLdKy7PEO67B16Fd9HA1ltfHI=,tag:GzZ8lXra5L1fjYEQPKty1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNzdxTWRnQUt1bkZEcGtj
            TzRSWFhEbm1LZzlGK3VyMEdNZEt1MWFxTDBNCkZBRWpubzQ3d29QOTNZd2d6RXlS
            Skg5dENrcDJrNFdmSUN6cjNPcE5aSTAKLS0tIGdnck9qZjVKdHRiMndiZTNYNzE4
            c3J2MFZxOWxXU1dRNmF6WC9JQ0U2ZTQKUzQK2TpuTSJ6ZBZ11LI2m8JmRzUCxQ8e
            iEk9/IaqDc1oevHp93alcd/CydiQjpYph7c4pL94EwRWzFmXf4JuGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:15:41Z"
    mac: ENC[AES256_GCM,data:sDB4f+uZv5TTdjQaVVE4Ek2njuEAnwMGDXdlPFJNbXVe72ZulOPD3RtNJjFKXYTxBXJjqq2yRz23jZcu2CDcI8BNRbcfTj0ohJK3TL9dffjvVKsw1ZSKwGgeC36kypTulqu2fJKrTh5g3TCX0fLGoDTVlh9x0WXOw9IZlgZhYGQ=,iv:6t94LcKlIoAEbu3yhOFnxZK/gn9YDZBAJkt2DNmt8Jc=,tag:O+NND6axM1U6L7Wdc7HD4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
