---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - certificate-erinko.yaml
  - certificate-shadowmorph.yaml
  - external-vaderrp-dnsendpoint.yaml
  - gateway-internal.yaml
  - gateway-public.yaml
  - gatewayclass.yaml
  - httproute-traefik-dashboard.yaml
  - service-traefik-wg.yaml

