---
apiVersion: v1
kind: Service
metadata:
  name: traefik-wg
  namespace: network
spec:
  type: ClusterIP
  externalIPs: ["172.16.8.11"]
  selector:
    app.kubernetes.io/instance: traefik-network
    app.kubernetes.io/name: traefik
  ports:
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
