---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: parsedmarc-imap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: parsedmarc-imap
    creationPolicy: Owner
  data:
    - secretKey: IMAP_PASSWORD
      remoteRef:
        key: f736bb43-232f-45c3-bc6e-f0a08e0d77c1
        property: password
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: c9dd1a68-a9b3-471b-be19-ec3181ebebee
        property: aws_access_key_id
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: c9dd1a68-a9b3-471b-be19-ec3181ebebee
        property: aws_secret_access_key
    - secretKey: S3_REGION
      remoteRef:
        key: c9dd1a68-a9b3-471b-be19-ec3181ebebee
        property: aws_default_region
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: c9dd1a68-a9b3-471b-be19-ec3181ebebee
        property: aws_endpoint
