---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: parsedmarc-imap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: parsedmarc-imap
    creationPolicy: Owner
  data:
    - secretKey: IMAP_PASSWORD
      remoteRef:
        key: f736bb43-232f-45c3-bc6e-f0a08e0d77c1
        property: password
