---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-users-secret
  namespace: mail
spec:
  refreshInterval: 1h
  target:
    name: stalwart-users-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://stalwart:{{ .db_password }}@postgres18-rw.database.svc.cluster.local:5432/stalwart?search_path=directory"
        JWT_SECRET: "{{ .jwt_secret }}"
  data:
    - secretKey: db_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: db_password
    - secretKey: jwt_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: afda7dff-e1ac-4c30-9ec9-1f81ad1e9971
        property: jwt_secret
