---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medikabalans
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - externalsecret-settings.yaml
  - externalsecret-harbor-pull-secret.yaml
