---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse
  namespace: matrix
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
