---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyronautopalvelu
  namespace: flux-system
spec:
  decryption:
    provider: sops
  targetNamespace: kyronautopalvelu
  commonMetadata:
    labels:
      app.kubernetes.io/name: kyronautopalvelu
  path: ./kubernetes/apps/kyronautopalvelu/kyronautopalvelu/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
