---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: parsedmarc
  namespace: flux-system
spec:
  decryption:
    provider: sops
  targetNamespace: tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: parsedmarc
  path: "./kubernetes/apps/tools/parsedmarc/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
